### ISSUE TITLE
Add deployment process in readme

### ISSUE THREAD

**Issue by epoberezkin** [guardian/gu-who#58]
Thanks for the great work :)

Tried to deploy to heroku from the fork.
The app crashes with this error, the secret is missing, trying to figure it out...

```
2016-06-07T11:09:12.891646+00:00 heroku[router]: at=info method=GET path="/" host=mol-gu-who.herokuapp.com request_id=98116e43-c0f1-4cd1-a931-aa1c8e2118e2 fwd="195.234.242.6" dyno=web.1 connect=0ms service=271ms status=500 bytes=2296
2016-06-07T11:09:12.802735+00:00 app[web.1]: [error] p.a.l.CryptoConfigParser - The application secret has not been set, and we are in prod mode. Your application is not secure.
2016-06-07T11:09:12.807093+00:00 app[web.1]: [error] p.a.l.CryptoConfigParser - To set the application secret, please read http://playframework.com/documentation/latest/ApplicationSecret
2016-06-07T11:09:12.828670+00:00 app[web.1]: [error] p.c.s.n.PlayDefaultUpstreamHandler - Cannot invoke the action
2016-06-07T11:09:12.828680+00:00 app[web.1]: com.google.inject.ProvisionException: Unable to provision, see the following errors:
2016-06-07T11:09:12.828702+00:00 app[web.1]: 
2016-06-07T11:09:12.828703+00:00 app[web.1]: 1) Error in custom provider, @70b975c16: Configuration error
2016-06-07T11:09:12.828704+00:00 app[web.1]:   while locating play.api.libs.CryptoConfigParser
2016-06-07T11:09:12.828705+00:00 app[web.1]:     for parameter 0 at play.api.libs.Crypto.<init>(Crypto.scala:282)
2016-06-07T11:09:12.828705+00:00 app[web.1]:   while locating play.api.libs.CryptoConfig
2016-06-07T11:09:12.828706+00:00 app[web.1]:   at play.api.inject.BuiltinModule.bindings(BuiltinModule.scala:49):
2016-06-07T11:09:12.828707+00:00 app[web.1]: Binding(class play.api.libs.Crypto to self) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)
2016-06-07T11:09:12.828707+00:00 app[web.1]:   while locating play.api.libs.Crypto
2016-06-07T11:09:12.828708+00:00 app[web.1]: 
2016-06-07T11:09:12.828710+00:00 app[web.1]: 	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051) ~[com.google.inject.guice-4.0.jar:na]
2016-06-07T11:09:12.828708+00:00 app[web.1]: 1 error
2016-06-07T11:09:12.828711+00:00 app[web.1]: 	at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:316) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
2016-06-07T11:09:12.828711+00:00 app[web.1]: 	at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:321) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
2016-06-07T11:09:12.828712+00:00 app[web.1]: 	at play.api.Application$$anonfun$instanceCache$1.apply(Application.scala:235) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
2016-06-07T11:09:12.828712+00:00 app[web.1]: 	at play.api.Application$$anonfun$instanceCache$1.apply(Application.scala:235) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
2016-06-07T11:09:12.828709+00:00 app[web.1]: 	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1025) ~[com.google.inject.guice-4.0.jar:na]
2016-06-07T11:09:12.828713+00:00 app[web.1]: 	at play.utils.InlineCache.fresh(InlineCache.scala:69) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
2016-06-07T11:09:12.828714+00:00 app[web.1]: 	at play.api.libs.Crypto$.crypto(Crypto.scala:43) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
2016-06-07T11:09:12.828713+00:00 app[web.1]: 	at scala.Option.fold(Option.scala:158) ~[org.scala-lang.scala-library-2.11.7.jar:na]
2016-06-07T11:09:12.828713+00:00 app[web.1]: 	at play.utils.InlineCache.apply(InlineCache.scala:55) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
2016-06-07T11:09:12.828716+00:00 app[web.1]: 	at play.api.libs.CryptoConfigParser.get(Crypto.scala:197) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
2016-06-07T11:09:12.828715+00:00 app[web.1]: 	at play.api.libs.CryptoConfigParser.get$lzycompute(Crypto.scala:236) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
2016-06-07T11:09:12.828714+00:00 app[web.1]: Caused by: play.api.PlayException: Configuration error[Application secret not set]
2016-06-07T11:09:12.828716+00:00 app[web.1]: 	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72) ~[com.google.inject.guice-4.0.jar:na]
2016-06-07T11:09:12.828717+00:00 app[web.1]: 	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61) ~[com.google.inject.guice-4.0.jar:na]
2016-06-07T11:09:12.828716+00:00 app[web.1]: 	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81) ~[com.google.inject.guice-4.0.jar:na]
2016-06-07T11:09:12.828717+00:00 app[web.1]: 	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62) ~[com.google.inject.guice-4.0.jar:na]
2016-06-07T11:09:12.828718+00:00 app[web.1]: 	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38) ~[com.google.inject.guice-4.0.jar:na]
2016-06-07T11:09:12.828718+00:00 app[web.1]: 	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104) ~[com.google.inject.guice-4.0.jar:na]
2016-06-07T11:09:12.828718+00:00 app[web.1]: 	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62) ~[com.google.inject.guice-4.0.jar:na]
2016-06-07T11:09:12.828715+00:00 app[web.1]: 	at play.api.libs.CryptoConfigParser.get(Crypto.scala:203) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
2016-06-07T11:09:12.838948+00:00 app[web.1]:  
2016-06-07T11:09:12.838949+00:00 app[web.1]: play.api.UnexpectedException: Unexpected exception[ProvisionException: Unable to provision, see the following errors:
2016-06-07T11:09:12.838945+00:00 app[web.1]: 
2016-06-07T11:09:12.838947+00:00 app[web.1]: ! @70b975c29 - Internal server error, for (GET) [/] ->
2016-06-07T11:09:12.838949+00:00 app[web.1]: 
2016-06-07T11:09:12.838929+00:00 app[web.1]: [error] application - 
2016-06-07T11:09:12.838950+00:00 app[web.1]: 1) Error in custom provider, @70b975c16: Configuration error
2016-06-07T11:09:12.838950+00:00 app[web.1]:   while locating play.api.libs.CryptoConfigParser
2016-06-07T11:09:12.838952+00:00 app[web.1]:     for parameter 0 at play.api.libs.Crypto.<init>(Crypto.scala:282)
2016-06-07T11:09:12.838953+00:00 app[web.1]:   at play.api.inject.BuiltinModule.bindings(BuiltinModule.scala:49):
2016-06-07T11:09:12.838954+00:00 app[web.1]: Binding(class play.api.libs.Crypto to self) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)
2016-06-07T11:09:12.838951+00:00 app[web.1]:   while locating play.api.libs.CryptoConfig
2016-06-07T11:09:12.838954+00:00 app[web.1]:   while locating play.api.libs.Crypto
2016-06-07T11:09:12.838955+00:00 app[web.1]: 1 error]
2016-06-07T11:09:12.838955+00:00 app[web.1]: 
2016-06-07T11:09:12.838958+00:00 app[web.1]: 	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
2016-06-07T11:09:12.838956+00:00 app[web.1]: 	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:261) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
2016-06-07T11:09:12.838957+00:00 app[web.1]: 	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
2016-06-07T11:09:12.838960+00:00 app[web.1]: 	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
2016-06-07T11:09:12.838961+00:00 app[web.1]: 	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:262) [com.typesafe.play.play-netty-server_2.11-2.4.4.jar:2.4.4]
2016-06-07T11:09:12.838960+00:00 app[web.1]: 	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:266) [com.typesafe.play.play-netty-server_2.11-2.4.4.jar:2.4.4]
2016-06-07T11:09:12.838963+00:00 app[web.1]: 	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [org.scala-lang.scala-library-2.11.7.jar:na]
2016-06-07T11:09:12.838959+00:00 app[web.1]: 	at play.api.mvc.WithFilters.onError(Filters.scala:93) [com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
2016-06-07T11:09:12.838963+00:00 app[web.1]: 	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [org.scala-lang.scala-library-2.11.7.jar:na]
2016-06-07T11:09:12.838966+00:00 app[web.1]: 1) Error in custom provider, @70b975c16: Configuration error
2016-06-07T11:09:12.838964+00:00 app[web.1]: 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.11.7.jar:na]
2016-06-07T11:09:12.838968+00:00 app[web.1]:     for parameter 0 at play.api.libs.Crypto.<init>(Crypto.scala:282)
2016-06-07T11:09:12.838965+00:00 app[web.1]: Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:
2016-06-07T11:09:12.838969+00:00 app[web.1]:   at play.api.inject.BuiltinModule.bindings(BuiltinModule.scala:49):
2016-06-07T11:09:12.838970+00:00 app[web.1]: Binding(class play.api.libs.Crypto to self) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)
2016-06-07T11:09:12.838966+00:00 app[web.1]: 
2016-06-07T11:09:12.838973+00:00 app[web.1]: 	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1025) ~[com.google.inject.guice-4.0.jar:na]
2016-06-07T11:09:12.838967+00:00 app[web.1]:   while locating play.api.libs.CryptoConfigParser
2016-06-07T11:09:12.838968+00:00 app[web.1]:   while locating play.api.libs.CryptoConfig
2016-06-07T11:09:12.838975+00:00 app[web.1]: 	at play.api.Application$$anonfun$instanceCache$1.apply(Application.scala:235) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
2016-06-07T11:09:12.838973+00:00 app[web.1]: 	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051) ~[com.google.inject.guice-4.0.jar:na]
2016-06-07T11:09:12.838976+00:00 app[web.1]: 	at play.api.Application$$anonfun$instanceCache$1.apply(Application.scala:235) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
2016-06-07T11:09:12.838975+00:00 app[web.1]: 	at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:316) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
2016-06-07T11:09:12.838971+00:00 app[web.1]: 
2016-06-07T11:09:12.838972+00:00 app[web.1]: 1 error
2016-06-07T11:09:12.838978+00:00 app[web.1]: 	at play.utils.InlineCache.apply(InlineCache.scala:55) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
2016-06-07T11:09:12.838978+00:00 app[web.1]: 	at scala.Option.fold(Option.scala:158) ~[org.scala-lang.scala-library-2.11.7.jar:na]
2016-06-07T11:09:12.838980+00:00 app[web.1]: Caused by: play.api.PlayException: Configuration error[Application secret not set]
2016-06-07T11:09:12.838971+00:00 app[web.1]:   while locating play.api.libs.Crypto
2016-06-07T11:09:12.839004+00:00 app[web.1]: 	at play.api.libs.CryptoConfigParser.get(Crypto.scala:197) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
2016-06-07T11:09:12.838981+00:00 app[web.1]: 	at play.api.libs.CryptoConfigParser.get(Crypto.scala:203) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
2016-06-07T11:09:12.839005+00:00 app[web.1]: 	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81) ~[com.google.inject.guice-4.0.jar:na]
2016-06-07T11:09:12.838977+00:00 app[web.1]: 	at play.utils.InlineCache.fresh(InlineCache.scala:69) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
2016-06-07T11:09:12.839005+00:00 app[web.1]: 	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72) ~[com.google.inject.guice-4.0.jar:na]
2016-06-07T11:09:12.838979+00:00 app[web.1]: 	at play.api.libs.Crypto$.crypto(Crypto.scala:43) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
2016-06-07T11:09:12.838974+00:00 app[web.1]: 	at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:321) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
2016-06-07T11:09:12.839025+00:00 app[web.1]: 	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104) ~[com.google.inject.guice-4.0.jar:na]
2016-06-07T11:09:12.839008+00:00 app[web.1]: 	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38) ~[com.google.inject.guice-4.0.jar:na]
2016-06-07T11:09:12.838980+00:00 app[web.1]: 	at play.api.libs.CryptoConfigParser.get$lzycompute(Crypto.scala:236) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
2016-06-07T11:09:12.839006+00:00 app[web.1]: 	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61) ~[com.google.inject.guice-4.0.jar:na]
2016-06-07T11:09:12.839007+00:00 app[web.1]: 	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62) ~[com.google.inject.guice-4.0.jar:na]
2016-06-07T11:09:12.839008+00:00 app[web.1]: 	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62) ~[com.google.inject.guice-4.0.jar:na]
```

**Comment by epoberezkin** [comment]
Ok, found it : https://github.com/MailOnline/gu-who/blob/master/heroku.md :)
